name: dev - Build Docker image and scan with orca
on:
  pull_request:
    types: [labeled, ready_for_review, review_requested]
    paths:
      - ".github/workflows/build-n-scan.yaml"
      - "src/**"
      - "docker/**"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
jobs:
  build-n-scan:
    name: build docker image and scan with orca

    runs-on: ubuntu-latest-4-cores
    environment: develop
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-23.04]
        python-version: ["3.9.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_PAT || github.token }}


      - name: Build docker image
        id: build-docker-image
        env:
          REPOSITORY: summarization-service
          PR_NUMBER: ${{ github.event.number }}
        run: |
          git_hash=$(git rev-parse --short "${{ github.sha }}")
          image_tag="pr-$PR_NUMBER-$git_hash"
          docker build -t $REPOSITORY:$image_tag -f docker/Dockerfile .
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_OUTPUT

      # Run Orca CLI against the previously created container image
      - name: Orca CLI - Security Scanning
        env:
          IMAGE_TAG: ${{ steps.build-docker-image.outputs.IMAGE_TAG }}
          ORCA_SECURITY_API_TOKEN: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          PROJECT_KEY: birch-engineering-summarization-service
          REPOSITORY: summarization-service
        run: |
          set +e
          apt update && apt install -y curl
          curl -sfL 'https://raw.GitHubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
          orca-cli -p "${PROJECT_KEY}" image scan $REPOSITORY:$IMAGE_TAG --disable-secret
      - name: "Setup tmate session"
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}