name: dev(JIT)- Build docker image and run tests, push to ECR if on develop branch
on:

  # pull_request:
  #   types: [labeled, ready_for_review, review_requested]
  #   paths:
  #     - ".github/workflows/build-n-push-jit.yaml"
  #     - "src/summ_service_jit/**"
  #     - "src/export_jit.py"
  #     - "src/setup.py"
  #     - "docker/jit.dockerfile"
  #     - "docker/docker-compose.jit.yaml"

  # push:
  #   branches:
  #     - develop
  #   paths:
  #     - ".github/workflows/build-n-push-jit.yaml"
  #     - "src/summ_service_jit/**"
  #     - "src/export_jit.py"
  #     - "src/setup.py"
  #     - "docker/jit.dockerfile"
  #     - "docker/docker-compose.jit.yaml"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
jobs:
  build-n-push-jit:
    name: build docker image and push to ecr dev

    runs-on: ubuntu-latest-4-cores
    environment: develop
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-23.04]
        python-version: ["3.9.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::804136630196:role/github-ecr-action
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup conda
        id: setup-conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          conda install pytorch=1.13.0 torchaudio=0.13.0 cpuonly  -c pytorch
          pip install src/fairseqForkSepFix
          pip install -r requirements.txt

      - name: test the docker image
        id: test-docker
        env:
          # remember to update this when releasing new models
          MODEL_NAME: v11.jit.pt
          API_KEY: ${{ secrets.API_KEY }}
          DEV_AWS_KEY: ${{ secrets.DEV_AWS_KEY }}
          DEV_AWS_SECRET: ${{ secrets.DEV_AWS_SECRET }}
          DEV_AWS_REGION: ${{ secrets.DEV_AWS_REGION }}
          SUMM_MODEL_VERSION: V11_complex_qa.general
          SUMM_MODEL_DOWNLOAD_PATH: s3://birch-dev-test-bucket/models/summarization/V11_complex_qa.general.zip
          SUMM_MODEL_NAME: finetune.qa.v11.16.3000.lr.2e-05.checkpoint_best
        run: |
          git_hash=$(git rev-parse --short "${{ github.sha }}")
          image_tag="jit-$git_hash"
          sed -i "s/image:.*/image: summarization-service:develop-$image_tag/" docker/docker-compose.jit.yaml
          python src/export_jit.py --model-dir data --output-model-name $MODEL_NAME
          docker compose -f docker/docker-compose.jit.yaml up &
          sleep 1000
          cat .github/test_data/ref/* > ref
          cat .github/test_data/output/* > out
          diff ref out
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_OUTPUT
      - name: Build, tag, and push docker image to Amazon ECR
        id: build-docker-push-ecr
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: summarization-service
          IMAGE_TAG: ${{ steps.test-docker.outputs.IMAGE_TAG }}
        if: contains('refs/heads/develop', github.ref)
        run: |
          docker tag summarization-service:develop-$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: "Setup tmate session [debug_enabled: ${{ inputs.debug_enabled }}]"
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}
