name: dev - Run unit tests with pytest
on:
  pull_request:
    types: [labeled, ready_for_review, review_requested]
    paths:
      - ".github/workflows/*"
      - "src/**"
      - "docker/**"


  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
jobs:
  test-with-docker:
    name: run tests
    runs-on: ubuntu-latest-4-cores
    environment: develop
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.9.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: docker-compose build container and run unit tests
        id: unit-test
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          export NUM_THREADS=$(nproc)
          docker-compose -f docker/docker-compose.ci.yaml build
          docker-compose -f docker/docker-compose.ci.yaml run summ-test

      - name: test with rmq
        id: integration-test-rmq
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          export NUM_THREADS=$(nproc)
          docker-compose -f docker/docker-compose.ci.yaml up summ-service &
          sleep 30
          docker-compose -f docker/docker-compose.ci.yaml logs summ-service
          docker-compose -f docker/docker-compose.ci.yaml up --exit-code-from send-msg -- send-msg
      - name: "Setup tmate session"
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}
