version: '3.7'

services:
  summ-test:
    user: "999:1099"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: summarization-service:ci
    environment:
      - AZURE_CLIENT_ID=$AZURE_CLIENT_ID
      - AZURE_TENANT_ID=$AZURE_TENANT_ID
      - AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET
      - SUMM_MODEL_VERSION=v9.general
      - SUMM_MODEL_DOWNLOAD_PATH=https://birchdevstorage.blob.core.windows.net/birchmodels/_DEV-RELEASE/summ/v9.general.zip
      - SUMM_MODEL_NAME=finetune.v9.fix.bh.review.pre2.lr.2e-05.tnu.1500.checkpoint_best
    restart: 'no'
    tty: true
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        pip install -r src/summ_service/test/requirements.txt
        pytest -x -vv --log-cli-level=WARNING -s src/summ_service/test/test_summ.py

  summ-service:
    user: "999:999"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: summarization-service:ci

    environment:
      - AZURE_CLIENT_ID=$AZURE_CLIENT_ID
      - AZURE_TENANT_ID=$AZURE_TENANT_ID
      - AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET
      - RABBITMQ_SERVER_URL=amqp://platform_producer:platform_producer@rabbitmq:5672
      - IP_QUEUE_NAME=summ_queue
      - NUM_THREADS=$NUM_THREADS
      - RESP_QUEUE_NAME=platform_resp_queue

      - SUMM_MODEL_VERSION=v9.general
      - SUMM_MODEL_DOWNLOAD_PATH=https://birchdevstorage.blob.core.windows.net/birchmodels/_DEV-RELEASE/summ/v9.general.zip
      - SUMM_MODEL_NAME=finetune.v9.fix.bh.review.pre2.lr.2e-05.tnu.1500.checkpoint_best

    restart: always
    tty: true
    # keeps running container after exit
    # command: tail -f /dev/null
    # entrypoint: [ "/bin/sh", "-c" ]
    command: python3 src/rmq_listener.py
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ../.github/rmq/definitions.json:/etc/rabbitmq/definitions.json
      - ../.github/rmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672

    restart: always

  send-msg:
    image: python:3.9-slim

    restart: 'no'
    # command: tail -f /dev/null
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        sleep 180
        apt update && apt install wget -y
        wget https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/v3.7.8/bin/rabbitmqadmin
        chmod 777 ./rabbitmqadmin
        ./rabbitmqadmin -H rabbitmq -u platform_producer -p platform_producer publish exchange=amq.default routing_key=summ_queue payload='{"req_body": {"text": "This is only a test example to check the function of this service"}, "job_id": 7574, "task_id": 17538}'
        sleep 60
        ./rabbitmqadmin -H rabbitmq -u platform_producer -p platform_producer get queue=platform_resp_queue ackmode=ack_requeue_false | grep 'PROCESSING'
        ./rabbitmqadmin -H rabbitmq -u platform_producer -p platform_producer get queue=platform_resp_queue ackmode=ack_requeue_false | grep 'COMPLETED'
    depends_on:
      - rabbitmq
      - summ-service
